name: open-webui-dev

services:
  # ollama service is commented out but kept for reference
  # ollama:
  #   ports:
  #     - 7869:11434
  #   volumes:
  #     - ollama:/root/.ollama
  #   container_name: ollama
  #   tty: true
  #   restart: always
  #   image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
  #   environment:
  #     - OLLAMA_KEEP_ALIVE=24h
  #     - OLLAMA_HOST=0.0.0.0
  #   networks:
  #     - ollama-docker

  frontend:
    build:
      context: .
      target: build
    env_file: '.env'
    command: ['npm', 'run', 'dev']
    depends_on:
      - backend
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - '8000:5173' # Changed from 3000 to 3001
    develop:
      watch:
        - action: sync
          path: ./src # Simplified path
          target: /app/src
        - action: rebuild
          path: package.json

  backend:
    build:
      context: .
      target: base
    command: ['bash', 'dev.sh']
    env_file: '.env'
    environment:
      - ENV=dev
      - WEBUI_AUTH=False
    volumes:
      - data:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - '8080:8080'
    restart: always
    develop:
      watch:
        - action: sync
          path: ./backend # Simplified path
          target: /app/backend
          ignore:
            - backend/data
        - action: rebuild
          path: backend/requirements.txt
    networks:
      - ollama-docker

volumes:
  data: {}
  ollama: {}

networks:
  ollama-docker:
    name: ollama-docker # Added explicit name
    driver: bridge # Added explicit driver
